from random import gammavariate

print("hello,welcome to our qup game.")
name = input("hello man what is your name?:")
print(f"hello {name}")
how = input("how are you?:")
print(f"some too.")
day = input("how is your day going?:")
print(f"ok.so,Let's play a game.")
print(f"I will ask you questions and you will answer.")
x = input("get it?:")
print(f"first questions:what is your birthday & date?")
bir = input("answer:")
print(f"well,what is your father name?")
fn = input("answer:")
print(f"well,what is your mother name?")
mn = input("answer:")
print(f"have you any borther/sister?")
os = input("answer:")
print(f"what is her name?")
sn = input("answer:")
print(f"what is your hobbe?")
hn = input("answer:")
print(f"ok.so,Your reply time is up.Now is our time.")
print("We are written a paragraph about your self from your giving answer.")
x = input("Do you want to see it?:")
print(f"hello {name}.your birthday on {bir}.your father name is {fn} & your mother name is {mn}.you have {os}.her name is {sn}.your hobbe is {hn} that is all.")
print("ok,good bye and take care.thanks.")
