name = input("what is your name?:")
want = input("what do you want?:")
print(name)
print(want)
print(f"hello {name} welcome in our website.you want some materials to lern prograom")
x = input("what is your faverite, python or java script?:")
print("your faverite is python.so, you can lern python on w3school")
x = input("have you any question?:")
print("ok.so,good bye & take care")
x = input("any requirement?:")
print("yes,i can.it is:https://www.w3schools.com/python/default.asp")
x = input("any requirement?:")
print("ok.so,good bye & take care")
